### ISSUE TITLE
Set proper RenderHints for better Image Scaling

### ISSUE THREAD

**Issue by g1plus** [hoehrmann/CutyCapt#2]
Scaled images (especially upscaled) are poorly interpolated (nearest neighbor?). CutyCapt should set (or allow through flags to set) renderhints to circumvent this.

Simple hack:

``` c++
painter.begin(&image);
painter.setRenderHint(QPainter::SmoothPixmapTransform);
painter.setRenderHint(QPainter::Antialiasing);
painter.setRenderHint(QPainter::TextAntialiasing);
painter.setRenderHint(QPainter::HighQualityAntialiasing);
mainFrame->render(&painter);
```

**Comment by hoehrmann** [comment]
I have tried this a couple of times on Windows, most recently with the current version of Qt 5.x for that system, and it had no effect that I could discern. Have you tried this, and on what kind of system?

**Comment by g1plus** [comment]
I tried it under linux (Arch Linux x64, qt5) because I ran into this problem when using the CSS-property background-size: cover
You can try:
`CutyCapt --url=http://webstandard.kulando.de/static/backgroundsize-css-tutorial --out=jagged.png --min-width=1920`

I attached two images, with and without RenderHints

![not_smooth](https://f.cloud.github.com/assets/1188373/762474/a97d1992-e7e8-11e2-8e26-11c9bc699040.png)
![smooth](https://f.cloud.github.com/assets/1188373/762475/a9bbb170-e7e8-11e2-8f2d-e146344164c3.png)

**Comment by uppalasx** [comment]
hoehrmann, how we can create CutyCapt.exe file in windows machine?
