### ISSUE TITLE
problem with compilation

### ISSUE THREAD

**Issue by copyhold** [hoehrmann/CutyCapt#3]
$ make
g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SVG_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSvg -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -o CutyCapt.o CutyCapt.cpp
CutyCapt.cpp: In member function ‘void CutyCapt::handleSslErrors(QNetworkReply_, QList<QSslError>)’:
CutyCapt.cpp:246:10: error: invalid use of incomplete type ‘class QNetworkReply’
In file included from /usr/include/qt4/QtWebKit/qgraphicswebview.h:24:0,
                 from /usr/include/qt4/QtWebKit/QtWebKit:3,
                 from CutyCapt.cpp:27:
/usr/include/qt4/QtWebKit/qwebpage.h:40:7: error: forward declaration of ‘class QNetworkReply’
CutyCapt.cpp: At global scope:
CutyCapt.cpp:244:1: warning: unused parameter ‘errors’ [-Wunused-parameter]
make: *_\* [CutyCapt.o] Error 1

**Comment by g1plus** [comment]
I run into this problem as well (I currently maintain the [AUR-package for Arch Linux](https://aur.archlinux.org/packages/cutycapt-qt4-svn/)) and solved it by adding 

``` c++
#include <QNetworkReply>
#include <QSslError>
```

to CutyCapt.cpp
This only applies to qt4. For qt5 no changes are needed.

**Comment by copyhold** [comment]
now I have
/usr/include/qt4/QtNetwork/qnetworkaccessmanager.h:64:7: error: forward declaration of ‘class QSslError’

**Comment by g1plus** [comment]
Sorry meant the .hpp
My patch-file looks like this:

`````` patch
--- cutycapt/cutycapt-code/CutyCapt/CutyCapt.hpp    2013-07-06 16:04:16.028585091 +0200
+++ CutyCapt.hpp    2013-07-06 15:59:06.000000000 +0200
@@ -1,4 +1,6 @@
 #include <QtWebKit>
+#include <QNetworkReply>
+#include <QSslError>

 #if QT_VERSION >= 0x050000
 #include <QtWebKitWidgets>```
``````

**Comment by copyhold** [comment]
ohh,
this way it worked
Thank you

**Comment by kolabse** [comment]
this way it worked
Thank you!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by swapnilsarwe** [comment]
had similar issue.... the solution worked for me too... cant is be fixed in the SVN repo directly

**Comment by sourabhmodi** [comment]
Worked...
Thank you ...!!!!

**Comment by chenyachao** [comment]
Cool! Worked for me, thank you!

**Comment by ghukill** [comment]
Worked for me as well.
